### ISSUE TITLE
Autochomp is confused if hammer is forward on entry

### ISSUE THREAD

**Issue by contradict** [jaschalittle/Chomp#2]
(Separate bug for another time: when you enter AutoChomp with the hammer already forward, the machine freaks out and tries to fire the hammer over and over in quick succession and won't stop when you turn AutoChomp off - you have to disable the weapons. This is pretty safe, because it just sits there and oscillates at BDC wasting nitrogen, but is still maybe worth someday addressing.)

**Comment by ghost** [comment]
Fixed by https://github.com/jaschalittle/Chomp/pull/11
